name: Upload Website
on: 
  push:
jobs:
  build:
    runs-on: mac-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
  deploy:
    needs: build 
    runs-on: macOS-latest 
    - name: Upload
  run: AWS_ACCESS_KEY_ID=${{secrets.S3_KEY}} AWS_SECRET_ACCESS_KEY=${{secrets.S3_SECRET_KEY}} aws s3 sync . s3://<hassan-bazzifullstackbankingapplication>/ --acl public-read --no-progress
  working-directory: <directory-to-sync>