name: Deploy CDK
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
<<<<<<< HEAD
      - name: Checkout code
        uses: actions/checkout@v2
=======
      - uses: actions/checkout@master
      - uses: udondan/cdk-nodejs@v0.3.1
>>>>>>> parent of 1556300 (Update nodejs.yml)
        with:
          fetch-depth: 1
      - name: Deploy
        uses: udondan/cdk-nodejs@v0.3.1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  